Repository bside-tinkerbell/Waving-iOS, pull requests merged in 2023-12, with the labels that each got.

#93 [CHORE] 세팅 업그레이드
  .github/ISSUE_TEMPLATE/💛-issue-template-💛-.md
  .github/pull_request_template.md
  README.md
Labels: ⚙️ Chore

#88 나의 지인 화면에서 이름 탭했을 때 동작 안 하는 버그
  Waving-iOS.xcodeproj/project.pbxproj
  Waving-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Waving-iOS/Common/PhoneNumberManager.swift
  Waving-iOS/Presentation/Friends/ViewModel/FriendsViewModel.swift
Labels: 🐛 Fix

#95 [FEAT] 1.0.0.3 심사 리젝 대응 (지인 연락하기 기능 추가)
  Waving-iOS.xcodeproj/project.pbxproj
  Waving-iOS/Data/API/Friends/FriendsEndpoint.swift
  Waving-iOS/Data/DTO/Friends/GetFriendsDTO.swift
  Waving-iOS/Domain/Entity/Friends/GetFriendsEntity.swift
  Waving-iOS/Domain/Entity/Friends/GetFriendsProfileEntity.swift
  Waving-iOS/Presentation/FriendProfile/View/TopProfileView.swift
  Waving-iOS/Presentation/FriendProfile/ViewController/FriendProfileViewController.swift
  Waving-iOS/Presentation/FriendProfile/ViewModel/FriendProfileViewModel.swift
  Waving-iOS/Presentation/Friends/View/FriendsContactCollectionViewCell.swift
  Waving-iOS/Presentation/Friends/View/FriendsListView.swift
  Waving-iOS/Presentation/Friends/ViewModel/FriendsViewModel.swift
  Waving-iOS/Presentation/MainTabBar/ViewController/FriendsViewController.swift
Labels: ⭐️ Feat
